mappings:
  - deprecatedAPI: "apiVersion: extensions/v1beta1\nkind: Deployment"
    newAPI: "apiVersion: apps/v1\nkind: Deployment"
    deprecatedInVersion: "v1.9"
    removedInVersion: "v1.16"
  - deprecatedAPI: "apiVersion: apps/v1beta1\nkind: Deployment"
    newAPI: "apiVersion: apps/v1\nkind: Deployment"
    deprecatedInVersion: "v1.9"
    removedInVersion: "v1.16"
  - deprecatedAPI: "apiVersion: apps/v1beta2\nkind: Deployment"
    newAPI: "apiVersion: apps/v1\nkind: Deployment"
    deprecatedInVersion: "v1.9"
    removedInVersion: "v1.16"
  - deprecatedAPI: "apiVersion: apps/v1beta1\nkind: StatefulSet"
    newAPI: "apiVersion: apps/v1\nkind: StatefulSet"
    deprecatedInVersion: "v1.9"
    removedInVersion: "v1.16"
  - deprecatedAPI: "apiVersion: apps/v1beta2\nkind: StatefulSet"
    newAPI: "apiVersion: apps/v1\nkind: StatefulSet"
    deprecatedInVersion: "v1.9"
    removedInVersion: "v1.16"
  - deprecatedAPI: "apiVersion: extensions/v1beta1\nkind: DaemonSet"
    newAPI: "apiVersion: apps/v1\nkind: DaemonSet"
    deprecatedInVersion: "v1.9"
    removedInVersion: "v1.16"
  - deprecatedAPI: "apiVersion: apps/v1beta2\nkind: DaemonSet"
    newAPI: "apiVersion: apps/v1\nkind: DaemonSet"
    deprecatedInVersion: "v1.9"
    removedInVersion: "v1.16"
  - deprecatedAPI: "apiVersion: extensions/v1beta1\nkind: ReplicaSet"
    newAPI: "apiVersion: apps/v1\nkind: ReplicaSet"
    deprecatedInVersion: "v1.9"
    removedInVersion: "v1.16"
  - deprecatedAPI: "apiVersion: apps/v1beta1\nkind: ReplicaSet"
    newAPI: "apiVersion: apps/v1\nkind: ReplicaSet"
    deprecatedInVersion: "v1.9"
    removedInVersion: "v1.16"
  - deprecatedAPI: "apiVersion: apps/v1beta2\nkind: ReplicaSet"
    newAPI: "apiVersion: apps/v1\nkind: ReplicaSet"
    deprecatedInVersion: "v1.9"
    removedInVersion: "v1.16"
  - deprecatedAPI: "apiVersion: extensions/v1beta1\nkind: NetworkPolicy"
    newAPI: "apiVersion: networking.k8s.io/v1\nkind: NetworkPolicy"
    deprecatedInVersion: "v1.8"
    removedInVersion: "v1.16"
  - deprecatedAPI: "apiVersion: extensions/v1beta1\nkind: PodSecurityPolicy"
    newAPI: "apiVersion: policy/v1beta1\nkind: PodSecurityPolicy"
    deprecatedInVersion: "v1.10"
    removedInVersion: "v1.16"
  - deprecatedAPI: "apiVersion: apiextensions.k8s.io/v1beta1\nkind: CustomResourceDefinition"
    newAPI: "apiVersion: apiextensions.k8s.io/v1\nkind: CustomResourceDefinition"
    deprecatedInVersion: "v1.16"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: extensions/v1beta1\nkind: Ingress"
    newAPI: "apiVersion: networking.k8s.io/v1beta1\nkind: Ingress"
    deprecatedInVersion: "v1.14"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: networking.k8s.io/v1beta1\nkind: Ingress"
    newAPI: "apiVersion: networking.k8s.io/v1\nkind: Ingress"
    deprecatedInVersion: "v1.19"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1alpha1\nkind: ClusterRole"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: ClusterRole"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1alpha1\nkind: ClusterRoleList"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: ClusterRoleList"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1alpha1\nkind: ClusterRoleBinding"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: ClusterRoleBinding"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1alpha1\nkind: ClusterRoleBindingList"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: ClusterRoleBindingList"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1alpha1\nkind: Role"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: Role"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1alpha1\nkind: RoleList"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: RoleList"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1alpha1\nkind: RoleBinding"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: RoleBinding"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1alpha1\nkind: RoleBindingList"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: RoleBindingList"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1beta1\nkind: ClusterRole"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: ClusterRole"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1beta1\nkind: ClusterRoleList"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: ClusterRoleList"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1beta1\nkind: ClusterRoleBinding"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: ClusterRoleBinding"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1beta1\nkind: ClusterRoleBindingList"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: ClusterRoleBindingList"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1beta1\nkind: Role"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: Role"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1beta1\nkind: RoleList"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: RoleList"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1beta1\nkind: RoleBinding"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: RoleBinding"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1beta1\nkind: RoleBindingList"
    newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: RoleBindingList"
    deprecatedInVersion: "v1.17"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: apiregistration.k8s.io/v1beta1\nkind: APIService"
    newAPI: "apiVersion: apiregistration.k8s.io/v1\nkind: APIService"
    deprecatedInVersion: "v1.19"
    removedInVersion: "v1.22"
  - deprecatedAPI: "apiVersion: apiregistration.k8s.io/v1beta1\nkind: APIServiceList"
    newAPI: "apiVersion: apiregistration.k8s.io/v1\nkind: APIServiceList"
    deprecatedInVersion: "v1.19"
    removedInVersion: "v1.22"
